### ISSUE TITLE
Change the empty state of the Clients page to guide the user on Stripe synchronization

### ISSUE THREAD

**Issue by otech47** [setlife-network/trinary#397]
Before the first client is created, there should be some instructions on how the Stripe integrated client-customer sync works

## Tasks

- [x] Test backend functionalities to make sure all features still work as expected without any Stripe credentials
- [x] Provide a way for the frontend UI to know whether Stripe credentials are valid
- [x] Show instructions on how to use Stripe for client management (if valid Stripe credentials are detected)
- [x] Show instructions on how to deploy/configure the app to enable the Stripe integration

See https://github.com/setlife-network/trinary/blob/develop/src/components/ClientsEmptyState.js

### Stripe not detected copy

```
To integrate with Stripe for client management, please configure the application with valid Stripe credentials (see example environment configuration here https://github.com/setlife-network/trinary/blob/develop/.env.example#L13)

Please see the Stripe documentation (https://stripe.com/docs/keys) to generate valid credentials
```

### Stripe detected copy

```
Creating or updating a Stripe customer will trigger a synchronized Client

Any updates to the name and email of a Client will reflect in your Stripe Dashboard
```

**Comment by otech47** [comment]
Copy for this will be provided by @otech47
